FROM ubuntu:16.04
WORKDIR composer-tools
RUN  apt-get update && \
     apt-get install sudo
RUN  apt-get -y install build-essential libssl-dev
RUN  apt-get install -y curl
RUN  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
RUN  export NVM_DIR="$HOME/.nvm" ; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
     nvm && nvm install 8 && \
     nvm use 8 && \
     apt-get -y install apt-transport-https ca-certificates && \
     npm install node-gyp node-pre-gyp && \
     apt-get -y install python && \
     npm install composer-cli@0.19.14 && \
     npm install composer-rest-server@0.19.14 && \
     npm install generator-hyperledger-composer@0.19.14 && \
     npm install yo && \
     npm install composer-playground@0.19.14
